contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #plateviewer channel"
    url: https://nfcore.slack.com/channels/plateviewer
    about: Discussion about the nf-core/plateviewer pipeline
